import type { FeedPostData, Platform } from "@/lib/types";

export const FEED_POSTS: FeedPostData[] = [
  // ── Real photographs (~11) ──────────────────────
  {
    id: "post-01",
    username: "naturelens",
    displayName: "Nature Photography",
    avatarUrl: "https://picsum.photos/seed/naturelens/40/40",
    platform: "instagram",
    timestamp: "2h ago",
    imageUrl: "https://picsum.photos/seed/sunset-lake/600/600",
    caption:
      "Golden hour at the lake. No filter needed when nature does the work.",
    isAiGenerated: false,
    expectedConfidence: 0.92,
  },
  {
    id: "post-02",
    username: "streetcaptures",
    displayName: "Urban Shots",
    avatarUrl: "https://picsum.photos/seed/streetcap/40/40",
    platform: "x",
    timestamp: "3h ago",
    imageUrl: "https://picsum.photos/seed/city-rain/600/750",
    caption:
      "Rainy nights in the city hit different. NYC never sleeps, even in the rain.",
    isAiGenerated: false,
    expectedConfidence: 0.88,
  },
  {
    id: "post-03",
    username: "foodie_anna",
    displayName: "Anna Eats",
    avatarUrl: "https://picsum.photos/seed/foodieanna/40/40",
    platform: "reddit",
    timestamp: "4h ago",
    imageUrl: "https://picsum.photos/seed/pasta-dish/600/600",
    caption: "Homemade truffle pasta. Recipe in bio!",
    isAiGenerated: false,
    expectedConfidence: 0.95,
  },
  {
    id: "post-04",
    username: "wanderlust_mike",
    displayName: "Mike Travels",
    avatarUrl: "https://picsum.photos/seed/wandermike/40/40",
    platform: "facebook",
    timestamp: "5h ago",
    imageUrl: "https://picsum.photos/seed/mountain-hike/600/750",
    caption: "3am wake-up was worth it. Sunrise at 12,000ft.",
    isAiGenerated: false,
    expectedConfidence: 0.91,
  },
  // ── AI-generated images (~7) ────────────────────
  {
    id: "post-05",
    username: "dreamscapes_ai",
    displayName: "AI Dreamscapes",
    avatarUrl: "https://picsum.photos/seed/dreamscapes/40/40",
    platform: "instagram",
    timestamp: "1h ago",
    imageUrl: "https://picsum.photos/seed/floating-castle/600/600",
    caption: "What if cities floated in the clouds? Imagination has no limits.",
    isAiGenerated: true,
    expectedConfidence: 0.94,
  },
  {
    id: "post-06",
    username: "artbot_studio",
    displayName: "ArtBot",
    avatarUrl: "https://picsum.photos/seed/artbotstudio/40/40",
    platform: "x",
    timestamp: "2h ago",
    imageUrl: "https://picsum.photos/seed/cyber-portrait/600/600",
    caption: "Portrait study: neon cyberpunk vibes. What do you think?",
    isAiGenerated: true,
    expectedConfidence: 0.97,
  },
  {
    id: "post-07",
    username: "pixel_dreams",
    displayName: "Pixel Dreams",
    avatarUrl: "https://picsum.photos/seed/pixeldreams/40/40",
    platform: "tiktok",
    timestamp: "3h ago",
    imageUrl: "https://picsum.photos/seed/fantasy-forest/600/750",
    caption:
      "Lost in an enchanted forest. The light through the crystal trees is unreal.",
    isAiGenerated: true,
    expectedConfidence: 0.91,
  },
  // ── More real photographs ───────────────────────
  {
    id: "post-08",
    username: "dogsof_ig",
    displayName: "Dogs of Instagram",
    avatarUrl: "https://picsum.photos/seed/dogsofig/40/40",
    platform: "instagram",
    timestamp: "6h ago",
    imageUrl: "https://picsum.photos/seed/golden-retriever/600/600",
    caption: "Someone's ready for their walk. Those eyes though!",
    isAiGenerated: false,
    expectedConfidence: 0.93,
  },
  {
    id: "post-09",
    username: "coffeeculture",
    displayName: "Coffee Culture",
    avatarUrl: "https://picsum.photos/seed/coffeecult/40/40",
    platform: "x",
    timestamp: "7h ago",
    imageUrl: "https://picsum.photos/seed/latte-art/600/600",
    caption: "Today's latte art. The barista absolutely nailed it.",
    isAiGenerated: false,
    expectedConfidence: 0.89,
  },
  // ── More AI images ──────────────────────────────
  {
    id: "post-10",
    username: "neural_canvas",
    displayName: "Neural Canvas",
    avatarUrl: "https://picsum.photos/seed/neuralcanvas/40/40",
    platform: "threads",
    timestamp: "4h ago",
    imageUrl: "https://picsum.photos/seed/space-whale/600/600",
    caption:
      "Space whales migrating through the nebula. The universe is full of wonders we haven't discovered yet.",
    isAiGenerated: true,
    expectedConfidence: 0.96,
  },
  {
    id: "post-11",
    username: "synth_visions",
    displayName: "Synth Visions",
    avatarUrl: "https://picsum.photos/seed/synthvis/40/40",
    platform: "x",
    timestamp: "5h ago",
    imageUrl: "https://picsum.photos/seed/retro-future/600/750",
    caption:
      "Retrofuturism at its finest. What 1960s architects thought 2026 would look like.",
    isAiGenerated: true,
    expectedConfidence: 0.88,
  },
  // ── More real content ───────────────────────────
  {
    id: "post-12",
    username: "fitlife_josh",
    displayName: "Josh Fitness",
    avatarUrl: "https://picsum.photos/seed/fitjosh/40/40",
    platform: "linkedin",
    timestamp: "8h ago",
    imageUrl: "https://picsum.photos/seed/gym-workout/600/600",
    caption: "Leg day. No excuses. 5am grind never stops.",
    isAiGenerated: false,
    expectedConfidence: 0.9,
  },
  {
    id: "post-13",
    username: "bookworm_reads",
    displayName: "Bookworm",
    avatarUrl: "https://picsum.photos/seed/bookworm/40/40",
    platform: "x",
    timestamp: "9h ago",
    imageUrl: "https://picsum.photos/seed/cozy-reading/600/600",
    caption: "Sunday vibes. Hot tea, good book, rain outside. Perfect.",
    isAiGenerated: false,
    expectedConfidence: 0.87,
  },
  // ── Ambiguous posts (~2) ────────────────────────
  {
    id: "post-14",
    username: "mixed_media_art",
    displayName: "Mixed Media Art",
    avatarUrl: "https://picsum.photos/seed/mixedmedia/40/40",
    platform: "bluesky",
    timestamp: "6h ago",
    imageUrl: "https://picsum.photos/seed/abstract-blend/600/600",
    caption:
      "Blending digital techniques with traditional painting. Where does one end and the other begin?",
    isAiGenerated: false,
    expectedConfidence: 0.52,
  },
  {
    id: "post-15",
    username: "photo_enhance",
    displayName: "Photo Enhancement",
    avatarUrl: "https://picsum.photos/seed/photoenhance/40/40",
    platform: "x",
    timestamp: "10h ago",
    imageUrl: "https://picsum.photos/seed/enhanced-landscape/600/750",
    caption:
      "AI-enhanced photo restoration of my grandpa's 1960s slide collection. Technology meets nostalgia.",
    isAiGenerated: false,
    expectedConfidence: 0.48,
  },
  // ── More AI content ─────────────────────────────
  {
    id: "post-16",
    username: "gen_art_daily",
    displayName: "Generative Art",
    avatarUrl: "https://picsum.photos/seed/genartdaily/40/40",
    platform: "mastodon",
    timestamp: "7h ago",
    imageUrl: "https://picsum.photos/seed/alien-garden/600/600",
    caption:
      "Alien botanical garden. What plants would grow on a planet with two suns?",
    isAiGenerated: true,
    expectedConfidence: 0.93,
  },
  // ── Final real photos ───────────────────────────
  {
    id: "post-17",
    username: "concert_shots",
    displayName: "Concert Photography",
    avatarUrl: "https://picsum.photos/seed/concertshots/40/40",
    platform: "substack",
    timestamp: "12h ago",
    imageUrl: "https://picsum.photos/seed/live-concert/600/600",
    caption:
      "Last night was incredible. The energy in the crowd was unmatched.",
    isAiGenerated: false,
    expectedConfidence: 0.86,
  },
  {
    id: "post-18",
    username: "macro_world",
    displayName: "Macro World",
    avatarUrl: "https://picsum.photos/seed/macroworld/40/40",
    platform: "x",
    timestamp: "14h ago",
    imageUrl: "https://picsum.photos/seed/dewdrop-leaf/600/600",
    caption: "A whole universe in a single dewdrop. 100mm macro lens, f/2.8.",
    isAiGenerated: false,
    expectedConfidence: 0.94,
  },
  // ── Final AI image ──────────────────────────────
  {
    id: "post-19",
    username: "future_frames",
    displayName: "Future Frames",
    avatarUrl: "https://picsum.photos/seed/futureframes/40/40",
    platform: "medium",
    timestamp: "8h ago",
    imageUrl: "https://picsum.photos/seed/underwater-city/600/750",
    caption:
      "Underwater metropolis concept. Humanity's next frontier might be beneath the waves.",
    isAiGenerated: true,
    expectedConfidence: 0.95,
  },
  {
    id: "post-20",
    username: "sunset_chaser",
    displayName: "Sunset Chaser",
    avatarUrl: "https://picsum.photos/seed/sunsetchaser/40/40",
    platform: "instagram",
    timestamp: "16h ago",
    imageUrl: "https://picsum.photos/seed/beach-sunset/600/600",
    caption:
      "Another day, another sunset. This one from Malibu. Nature's daily masterpiece.",
    isAiGenerated: false,
    expectedConfidence: 0.91,
  },
];
