"use client";

type SynthIDResult = "watermarked" | "not_watermarked" | "uncertain";

interface SynthIDBadgeProps {
  synthidResult: SynthIDResult | null | undefined;
}

function ShieldCheckIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      className="shrink-0"
    >
      <path
        d="M10 1.5L3 4.5V9.5C3 13.64 6.04 17.46 10 18.5C13.96 17.46 17 13.64 17 9.5V4.5L10 1.5Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinejoin="round"
        fill="currentColor"
        fillOpacity="0.12"
      />
      <path
        d="M7 10L9 12L13 8"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function DashIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      className="shrink-0"
    >
      <circle
        cx="10"
        cy="10"
        r="7.5"
        stroke="currentColor"
        strokeWidth="1.5"
        fill="currentColor"
        fillOpacity="0.08"
      />
      <path
        d="M7 10H13"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
      />
    </svg>
  );
}

function QuestionIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      className="shrink-0"
    >
      <circle
        cx="10"
        cy="10"
        r="7.5"
        stroke="currentColor"
        strokeWidth="1.5"
        fill="currentColor"
        fillOpacity="0.12"
      />
      <path
        d="M8 7.5C8 6.4 8.9 5.5 10 5.5C11.1 5.5 12 6.4 12 7.5C12 8.6 11.1 9.5 10 9.5V11"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="10" cy="13.5" r="0.75" fill="currentColor" />
    </svg>
  );
}

const CONFIG: Record<
  SynthIDResult,
  {
    container: string;
    text: string;
    message: string;
    ariaLabel: string;
    Icon: () => React.JSX.Element;
  }
> = {
  watermarked: {
    container: "bg-green-500/10 border-green-500/20",
    text: "text-green-700",
    message:
      "SynthID Watermark Detected \u2014 This content was generated by a Google AI model and contains an embedded digital watermark",
    ariaLabel: "SynthID watermark detected",
    Icon: ShieldCheckIcon,
  },
  not_watermarked: {
    container: "bg-secondary/5 border-secondary/10",
    text: "text-secondary/50",
    message: "No SynthID Watermark Found",
    ariaLabel: "No SynthID watermark found",
    Icon: DashIcon,
  },
  uncertain: {
    container: "bg-amber-500/10 border-amber-500/20",
    text: "text-amber-700",
    message:
      "SynthID Detection Uncertain \u2014 Could not determine watermark status",
    ariaLabel: "SynthID watermark detection uncertain",
    Icon: QuestionIcon,
  },
};

export function SynthIDBadge({ synthidResult }: SynthIDBadgeProps) {
  if (synthidResult == null) return null;

  const { container, text, message, ariaLabel, Icon } = CONFIG[synthidResult];

  return (
    <div
      className={`rounded-xl border p-4 flex items-center gap-3 ${container}`}
      role="status"
      aria-label={ariaLabel}
    >
      <span className={text}>
        <Icon />
      </span>
      <p className={`text-sm font-medium leading-snug ${text}`}>{message}</p>
    </div>
  );
}
