// frontend/src/lib/detection/text-pipeline.ts — Text detection cascading pipeline (v5.0)

import type { TextDetectionResult, SentenceScore, MethodScore } from "@/lib/types";
import { DETECTION_CONFIG } from "@/lib/detection-config";
import { logger } from "@/lib/logger";
import { computeTextStats } from "@/lib/mock-detectors";
import { precise } from "./helpers";
import { mapVerdict, buildFeatureVector } from "./verdict";
import { methodD_statistical, scoreSentencesReal } from "./statistical";
import { getProTextMethods } from "./pro-loader";
import type { PangramResult } from "./pro-loader";

export async function realTextDetection(
  text: string,
): Promise<TextDetectionResult> {
  try {
    const textStats = computeTextStats(text);

    if (text.length < 20) {
      const stats = methodD_statistical(text, textStats);
      const featureVector = buildFeatureVector(stats);
      return {
        verdict: "light_edit",
        confidence: 0.0,
        ai_probability: 0.5,
        model_used: "deberta+statistical",
        text_stats: textStats,
        caveat:
          "Text too short for reliable detection (minimum 20 characters recommended).",
        trust_score: 0.5,
        classification: "light_edit",
        edit_magnitude: 0.0,
        feature_vector: featureVector,
        sentence_scores: [],
      };
    }

    const pro = await getProTextMethods();

    // Stage 1: SynthID Text (Google Gemini watermark detection)
    const synthidResult = pro ? await pro.methodSynthID_text(text).catch(() => null) : null;

    if (synthidResult === "watermarked") {
      const stats = methodD_statistical(text, textStats);
      const featureVector = buildFeatureVector(stats);
      const mapping = mapVerdict(
        DETECTION_CONFIG.text.synthidOverride,
        text.length,
      );
      return {
        verdict: mapping.verdict,
        confidence: mapping.confidence,
        ai_probability: DETECTION_CONFIG.text.synthidOverride,
        model_used: "synthid:watermarked",
        text_stats: textStats,
        caveat:
          "Google SynthID watermark detected — this text was generated by a Google Gemini model.",
        trust_score: mapping.trust_score,
        classification: mapping.verdict,
        edit_magnitude: mapping.edit_magnitude,
        feature_vector: featureVector,
        sentence_scores: scoreSentencesReal(
          text,
          DETECTION_CONFIG.text.synthidOverride,
        ),
        method_scores: {
          pangram: {
            score: 0,
            weight: DETECTION_CONFIG.display.textMethods.pangram.weight,
            label: DETECTION_CONFIG.display.textMethods.pangram.label,
            available: false,
            status: "not_run",
          },
          synthid_text: {
            score: 1.0,
            weight: 1.0,
            label: DETECTION_CONFIG.display.textMethods.synthidText.label,
            available: true,
            status: "success",
          },
          statistical: {
            score: stats.signal,
            weight: DETECTION_CONFIG.display.textMethods.statistical.weight,
            label: DETECTION_CONFIG.display.textMethods.statistical.label,
            available: true,
            status: "success",
          },
        },
        synthid_text_result: "watermarked",
      };
    }

    // Stage 2: Pangram API (99.85% accuracy commercial detector)
    const pangramResult = pro ? await pro.methodP_pangram(text).catch(() => null) : null;

    if (pangramResult !== null) {
      const stats = methodD_statistical(text, textStats);
      const featureVector = buildFeatureVector(stats);

      let aiProbability = pangramResult.score;

      if (text.length < DETECTION_CONFIG.text.shortTextScalingThreshold) {
        const lengthPenalty =
          text.length / DETECTION_CONFIG.text.shortTextScalingThreshold;
        aiProbability = precise(0.5 + (aiProbability - 0.5) * lengthPenalty);
      }

      const mapping = mapVerdict(aiProbability, text.length);

      let sentenceScores = scoreSentencesReal(text, aiProbability);
      if (pangramResult.windows && pangramResult.windows.length > 0) {
        const pangramSentences: SentenceScore[] = pangramResult.windows.map(
          (w) => {
            const startIdx = text.indexOf(w.text);
            return {
              text: w.text,
              ai_probability: w.ai_assistance_score,
              start_index: startIdx >= 0 ? startIdx : 0,
              end_index:
                startIdx >= 0 ? startIdx + w.text.length : w.text.length,
            };
          },
        );
        if (pangramSentences.length > 0) sentenceScores = pangramSentences;
      }

      const synthidAvailable =
        synthidResult !== null && synthidResult !== undefined;
      const methodScores: Record<string, MethodScore> = {
        pangram: {
          score: pangramResult.score,
          weight: 1.0,
          label: DETECTION_CONFIG.display.textMethods.pangram.label,
          available: true,
          status: "success",
        },
        synthid_text: {
          score: synthidAvailable
            ? synthidResult === "not_watermarked"
              ? 0.0
              : 0.5
            : 0,
          weight: 0.0,
          label: DETECTION_CONFIG.display.textMethods.synthidText.label,
          available: synthidAvailable,
          status: synthidAvailable ? "success" : "unavailable",
        },
        statistical: {
          score: stats.signal,
          weight: DETECTION_CONFIG.display.textMethods.statistical.weight,
          label: DETECTION_CONFIG.display.textMethods.statistical.label,
          available: true,
          status: "success",
        },
      };

      return {
        verdict: mapping.verdict,
        confidence: mapping.confidence,
        ai_probability: aiProbability,
        model_used:
          "pangram" + (synthidResult ? "+synthid:" + synthidResult : ""),
        text_stats: textStats,
        caveat: mapping.caveat,
        trust_score: mapping.trust_score,
        classification: mapping.verdict,
        edit_magnitude: mapping.edit_magnitude,
        feature_vector: featureVector,
        sentence_scores: sentenceScores,
        method_scores: methodScores,
        pangram_classification: pangramResult.classification,
        pangram_windows: pangramResult.windows?.map((w) => ({
          start: text.indexOf(w.text),
          end: text.indexOf(w.text) + w.text.length,
          ai_assistance_score: w.ai_assistance_score,
          classification: w.label,
          confidence:
            w.confidence === "High"
              ? 0.9
              : w.confidence === "Medium"
                ? 0.7
                : 0.5,
        })),
        synthid_text_result: synthidResult,
      };
    }

    // Stage 3: Statistical-only fallback when both primary APIs are unavailable
    logger.warn("text-pipeline", "Primary text APIs unavailable, using statistical fallback");
    const statsSignal = methodD_statistical(text, textStats);
    const featureVector = buildFeatureVector(statsSignal);
    const statMapping = mapVerdict(statsSignal.signal, text.length);

    return {
      verdict: statMapping.verdict,
      confidence: statMapping.confidence,
      ai_probability: statsSignal.signal,
      model_used: "statistical-only:12-features",
      text_stats: textStats,
      caveat:
        "Primary APIs unavailable. Result based on statistical analysis only — lower confidence.",
      trust_score: statMapping.trust_score,
      classification: statMapping.verdict,
      edit_magnitude: statMapping.edit_magnitude,
      feature_vector: featureVector,
      sentence_scores: [],
      method_scores: {
        pangram: {
          score: 0,
          weight: 0.5,
          label: DETECTION_CONFIG.display.textMethods.pangram.label,
          available: false,
          status: "unavailable",
          tier: "primary" as const,
        },
        synthid_text: {
          score: 0,
          weight: 0.3,
          label: "SynthID Text (Google)",
          available: false,
          status: "unavailable",
          tier: "watermark" as const,
        },
        statistical: {
          score: statsSignal.signal,
          weight: 1.0,
          label: "Statistical Analysis (12 features)",
          available: true,
          status: "success",
          tier: "fallback" as const,
        },
      },
      synthid_text_result: null,
    };
  } catch (error) {
    logger.error("text-pipeline", "Real text detection failed", error);
    throw error;
  }
}
